[package]
name = "tftp-rs"
version = "0.3.0"
edition = "2018"
authors = ["Tom Dyas <tom@shoalsoftware.com>"]

[dependencies]
ascii = "1.0"
async-trait = "0.1"
bytes = "0.4"
futures = "0.3"
tempfile = "3.1"
tokio = "=0.2.0-alpha.6"
