[package]
name = "tftp-rs"
version = "0.1.0"
edition = "2018"
authors = ["Tom Dyas <tom@shoalsoftware.com>"]

[dependencies]
ascii = "0.9.2"
bytes = "0.4.12"
tokio = "=0.2.0-alpha.1"
async-trait = "0.1.9"
pin-utils = "0.1.0-alpha.4"
